/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, memo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import { gsap } from 'gsap';

// useGLTF: GLB model ko load karta hai, nodes/materials expose karta hai
function PlanetComponent(props) {
  const { nodes, materials } = useGLTF('/models/Planet.glb')
  // Refs: alag-alag parts ko animate/transform karne ke liye
  const shapeContainer = useRef(null) ;
  const shpereContainer = useRef(null) ;
  const ringContainer = useRef(null) ;


  // Intro animation: planet neeche se aata hai, phir rotation easing
  useGSAP ( () => {
    const tl = gsap.timeline();
    tl.from(shapeContainer.current.position,{
      y:5,
      duration:3,
      ease:"circ.out",
     });
     tl.from(shpereContainer.current.rotation,{
      x:0,
      y:Math.PI,
      z:-Math.PI,
      duration:10,
      ease:"power1.inOut",
     },"-=0.25");
     tl.from(ringContainer.current.rotation,{
      x:0,
      y:0,
      z:0,
      duration:10,
      ease:"power1.inOut",
     },"<");
  },[]);
  return (
    
    <group ref = {shapeContainer} {...props} dispose={null}>
      <group ref = {shpereContainer} rotation={[Math.PI / 2, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Material.002']}
        rotation={[0, 0, 0.741]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere2.geometry}
        material={materials['Material.001']}
        position={[0.647, 1.03, -0.724]}
        rotation={[0, 0, 0.741]}
        scale={0.223}
      />
      </group>
      <mesh
      ref = {ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials['Material.001']}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  )
}

// Wrap with memo for performance and export
export const Planet = memo(PlanetComponent);

// Preload: model ko pehle se fetch karlo taaki render time par fast ho
useGLTF.preload('/models/Planet.glb')

